name: Python application

on:
  push:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        docker login -u "jupitersmoons" --password-stdin=${{ secrets.DOCKERPW }}
        docker image build -t jupitersmoons/gitops:hellov1.2 .
        docker push jupitersmoons/gitops:hellov1.2
